### ISSUE TITLE
一直关注你 ，准备去ali了么 恭喜哈， 这么巧 我也是 哪个业务线了

### ISSUE THREAD

**Issue by Lijian1122** [hishark/777-Interview-Notes#3]

**Comment by hishark** [comment]
哇好巧！也恭喜你哈哈哈哈！我已经入职一周啦，在蚂蚁的数字金融线，等你入职了钉钉找我哇我花名是元七！^ ^

**Comment by Lijian1122** [comment]
> 哇好巧！也恭喜你哈哈哈哈！我已经入职一周啦，在蚂蚁的数字金融线，等你入职了钉钉找我哇我花名是元七！^ ^
哈哈 好的
